"""参考范本：系列级"完美模板"，展示公共代码标准写法，既供工艺契约核验，也供 LLM 参考指挥。"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any

_log = logging.getLogger(__name__)

# 参考范本目录（forge_templates/reference/）
_REF_DIR = Path(__file__).resolve().parent / "forge_templates" / "reference"


# ────────────────────────── 系列参考范本 ──────────────────────────
# 每个范本 = 无具体数值的完整工程代码骨架，展示"工程级公共代码"标准写法：
#   1. 文件头注释（@file/@brief/@attention 生成物标注）
#   2. main.c 公共代码（HAL_Init → SystemClock_Config → 外设初始化区
#      → while(1) → Error_Handler，USER CODE 区 CubeMX 兼容）
#   3. 外设 init 标准五段式（句柄声明 → 时钟使能 → 参数配置
#      → Init 校验 → 引脚复用）
#   4. 收尾（DeInit 反初始化）

REFERENCE_TEMPLATES: dict[str, dict[str, Any]] = {
    # ═══ F407 大类参考范本（M4F/168MHz，APM32F407/STM32F407 兼容）═══
    "ref_f407": {
        "id": "ref_f407",
        "version": "v1",
        "kind": "reference",          # 参考范本
        "series": "F407",
        "core": "Cortex-M4F",
        "max_clock_mhz": 168,
        "compatible_chips": ["APM32F407VGT6", "STM32F407VGT6", "STM32F407ZGT6"],
        "structure_note": (
            "F407 系列公共代码标准（无具体数值的参考范本）。"
            "功能模板按此结构打：文件头 → 句柄声明 → 时钟使能 → 参数配置"
            "→ Init 校验 → 引脚复用 → 主循环 → 收尾。细化芯片模板按此核验。"
        ),
        "main_c_skeleton": """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : <功能描述>（F407 系列参考范本）
  * @attention
  * Generated by Agent-S-Embedded | 参考范本: ref_f407
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private typedef -----------------------------------------------------------*/

/* Private define ------------------------------------------------------------*/

/* Private macro -------------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
<外设初始化函数原型>      /* 每个功能一个 MX_<外设>_Init(void) */

/* USER CODE BEGIN 0 */
<用户前置代码>
/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* MCU Configuration --------------------------------------------------------*/
  HAL_Init();
  SystemClock_Config();

  /* USER CODE BEGIN 2 */
  MX_<外设1>_Init();          /* 功能初始化（三段式 init） */
  MX_<外设2>_Init();
  /* USER CODE END 2 */

  /* Infinite loop */
  while (1)
  {
    <功能主循环逻辑>          /* 三段式 loop：轮询/事件/状态机 */
    /* USER CODE END WHILE */
  }
  /* USER CODE END 3 */
}

/**
  * @brief  System Clock Configuration（F407: HSE 8MHz → PLL → 168MHz）
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = <PLLM>;            /* 无具体数值——按芯片实际 */
  RCC_OscInitStruct.PLL.PLLN = <PLLN>;
  RCC_OscInitStruct.PLL.PLLP = <PLLP>;
  RCC_OscInitStruct.PLL.PLLQ = <PLLQ>;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = <DIV>;
  RCC_ClkInitStruct.APB1CLKDivider = <DIV>;
  RCC_ClkInitStruct.APB2CLKDivider = <DIV>;
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_<N>) != HAL_OK)
  {
    Error_Handler();
  }
}

/* ===== 外设 init 标准五段式（范本：每个功能模板照此打） ===== */
void MX_<外设>_Init(void)
{
  /* ① 句柄声明（带模板前缀，防组合冲突） */
  <外设>_HandleTypeDef <前缀>_<外设> = {0};
  /* ② 时钟使能 */
  __HAL_RCC_<外设>_CLK_ENABLE();
  /* ③ 参数配置（Init 结构体逐字段） */
  <前缀>_<外设>.Instance = <外设实例>;
  <前缀>_<外设>.Init.<参数1> = <配置>;
  <前缀>_<外设>.Init.<参数2> = <配置>;
  /* ④ Init 校验（失败必进 Error_Handler） */
  if (HAL_<外设>_Init(&<前缀>_<外设>) != HAL_OK)
  {
    Error_Handler();
  }
  /* ⑤ 引脚复用（CubeMX 风格 GPIO AF 段；引脚由占位分配器决定） */
  __HAL_RCC_GPIO<端口>_CLK_ENABLE();
  GPIO_InitTypeDef <前缀>_gpio_init = {0};
  <前缀>_gpio_init.Pin = GPIO_PIN_<引脚>;
  <前缀>_gpio_init.Mode = GPIO_MODE_AF_PP;
  <前缀>_gpio_init.Pull = GPIO_NOPULL;
  <前缀>_gpio_init.Speed = GPIO_SPEED_FREQ_HIGH;
  <前缀>_gpio_init.Alternate = GPIO_AF<AF号>_<外设>;
  HAL_GPIO_Init(GPIO<端口>, &<前缀>_gpio_init);
  /* ⑥ 启动（Start/Enable） */
  HAL_<外设>_Start(&<前缀>_<外设>);
}

/* USER CODE BEGIN 4 */
/* 功能收尾段（deinit：反序收尾，后初始化先 DeInit） */
void MX_<外设>_DeInit(void)
{
  HAL_<外设>_DeInit(&<前缀>_<外设>);
}
/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  __disable_irq();
  while (1)
  {
  }
}
""",
        "keywords": ["f407 范本", "f407 参考", "f407 标准", "407 通用模板"],
    },

    # ═══ F103 大类参考范本（M3/72MHz，STM32F103 系列）═══
    "ref_f103": {
        "id": "ref_f103",
        "version": "v1",
        "kind": "reference",
        "series": "F103",
        "core": "Cortex-M3",
        "max_clock_mhz": 72,
        "compatible_chips": ["STM32F103C8T6", "STM32F103RCT6", "STM32F103ZET6"],
        "structure_note": (
            "F103 系列公共代码标准（无具体数值的参考范本）。"
            "与 F407 同构（句柄/时钟/参数/校验/引脚复用五段式），"
            "差异在时钟树（HSE 8MHz → 72MHz，无 PWR 电压缩放）与寄存器。"
        ),
        "main_c_skeleton": """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : <功能描述>（F103 系列参考范本）
  * @attention
  * Generated by Agent-S-Embedded | 参考范本: ref_f103
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private typedef -----------------------------------------------------------*/

/* Private define ------------------------------------------------------------*/

/* Private macro -------------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
<外设初始化函数原型>      /* 每个功能一个 MX_<外设>_Init(void) */

/* USER CODE BEGIN 0 */
<用户前置代码>
/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* MCU Configuration --------------------------------------------------------*/
  HAL_Init();
  SystemClock_Config();

  /* USER CODE BEGIN 2 */
  MX_<外设1>_Init();          /* 功能初始化（三段式 init） */
  MX_<外设2>_Init();
  /* USER CODE END 2 */

  /* Infinite loop */
  while (1)
  {
    <功能主循环逻辑>          /* 三段式 loop：轮询/事件/状态机 */
    /* USER CODE END WHILE */
  }
  /* USER CODE END 3 */
}

/**
  * @brief  System Clock Configuration（F103: HSE 8MHz → PLL → 72MHz）
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSEPredivValue = <DIV>;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = <MUL>;           /* F103 无 PLLM/PLLN，用 PLLMUL */
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = <DIV>;
  RCC_ClkInitStruct.APB1CLKDivider = <DIV>;
  RCC_ClkInitStruct.APB2CLKDivider = <DIV>;
  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_<N>) != HAL_OK)
  {
    Error_Handler();
  }
}

/* ===== 外设 init 标准五段式（范本：每个功能模板照此打） ===== */
void MX_<外设>_Init(void)
{
  /* ① 句柄声明（带模板前缀，防组合冲突） */
  <外设>_HandleTypeDef <前缀>_<外设> = {0};
  /* ② 时钟使能 */
  __HAL_RCC_<外设>_CLK_ENABLE();
  /* ③ 参数配置（Init 结构体逐字段） */
  <前缀>_<外设>.Instance = <外设实例>;
  <前缀>_<外设>.Init.<参数1> = <配置>;
  /* ④ Init 校验（失败必进 Error_Handler） */
  if (HAL_<外设>_Init(&<前缀>_<外设>) != HAL_OK)
  {
    Error_Handler();
  }
  /* ⑤ 引脚复用（CubeMX 风格 GPIO AF 段；引脚由占位分配器决定） */
  __HAL_RCC_GPIO<端口>_CLK_ENABLE();
  GPIO_InitTypeDef <前缀>_gpio_init = {0};
  <前缀>_gpio_init.Pin = GPIO_PIN_<引脚>;
  <前缀>_gpio_init.Mode = GPIO_MODE_AF_PP;
  <前缀>_gpio_init.Pull = GPIO_NOPULL;
  <前缀>_gpio_init.Speed = GPIO_SPEED_FREQ_HIGH;
  <前缀>_gpio_init.Alternate = GPIO_AF<AF号>_<外设>;
  HAL_GPIO_Init(GPIO<端口>, &<前缀>_gpio_init);
  /* ⑥ 启动（Start/Enable） */
  HAL_<外设>_Start(&<前缀>_<外设>);
}

/* USER CODE BEGIN 4 */
/* 功能收尾段（deinit：反序收尾，后初始化先 DeInit） */
void MX_<外设>_DeInit(void)
{
  HAL_<外设>_DeInit(&<前缀>_<外设>);
}
/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  __disable_irq();
  while (1)
  {
  }
}
""",
        "keywords": ["f103 范本", "f103 参考", "f103 标准", "103 通用模板"],
    },
}


class ReferenceTemplateStore:
    """参考范本库：按系列取"完美模板"（脚本核验 + LLM 参考）。"""

    def __init__(self, ref_dir: Path | str | None = None) -> None:
        self._ref_dir = Path(ref_dir or _REF_DIR)
        self._templates = dict(REFERENCE_TEMPLATES)
        self._load_disk()

    def _load_disk(self) -> None:
        """从磁盘加载归档范本（只增不减：磁盘只补新增，不覆盖内置）。"""
        if not self._ref_dir.exists():
            return
        for path in sorted(self._ref_dir.glob("*.json")):
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
                tid = data.get("id")
                if tid:
                    self._templates[tid] = data
            except (OSError, json.JSONDecodeError) as exc:
                _log.debug("RefStore: 范本加载失败 %s: %s", path, exc)

    # ---- 查询 ----

    def get(self, template_id: str) -> dict[str, Any] | None:
        return self._templates.get(template_id)

    def get_by_series(self, series: str) -> dict[str, Any] | None:
        """按系列名取范本（ref_f407 / F407 / f407 → 同）。"""
        key = str(series).upper().replace(" ", "")
        if key.startswith("REF_"):
            key = key[4:]
        for _tid, tpl in self._templates.items():
            if str(tpl.get("series", "")).upper() == key:
                return tpl
        return None

    def list_references(self) -> list[str]:
        return list(self._templates.keys())

    def skeleton(self, series: str) -> str:
        """取范本的 main.c 骨架（脚本核验对照 / LLM 参考）。"""
        tpl = self.get_by_series(series)
        if tpl:
            return str(tpl.get("main_c_skeleton", ""))
        return ""

    def structure_note(self, series: str) -> str:
        tpl = self.get_by_series(series)
        return str(tpl.get("structure_note", "")) if tpl else ""

    # ---- 归档 ----

    def archive_all(self, out_dir: Path | str | None = None) -> int:
        """归档全部范本到磁盘（只增不减）。"""
        out = Path(out_dir or self._ref_dir)
        out.mkdir(parents=True, exist_ok=True)
        count = 0
        for tid, tpl in self._templates.items():
            path = out / f"{tid}.json"
            if not path.exists():
                path.write_text(json.dumps(tpl, ensure_ascii=False, indent=2), encoding="utf-8")
                count += 1
        return count


def get_reference(series: str) -> str:
    """便捷入口：取系列范本骨架（无则返回空）。"""
    return ReferenceTemplateStore().skeleton(series)


def render_reference(series: str, chip: str) -> str:
    """把系列范本渲染成具体芯片范本（整体·细化）。

    念安 8-21「整体·细化」：范本分大面（系列级占位符 <PLLM>/<PLLN> 等）和
    细化（具体芯片值）。本函数把时钟占位符用具体芯片 clock_tree 填，生成「具体
    芯片范本」（展示样本，供对照校验 + LLM 参考）。引脚/外设占位符保留——它们是
    结构示意，拼装时由 PinAllocator/单区块具体化。

    无具体芯片 clock_tree → 返回系列级范本（大面兜底，防脱靶）。
    """
    tpl = ReferenceTemplateStore().get_by_series(series)
    if tpl is None:
        return ""
    skeleton = str(tpl.get("main_c_skeleton", ""))
    try:
        from knowledge.loaders.profile_manager import ProfileManager

        profile = ProfileManager().get_profile(chip)
    except Exception:  # noqa: BLE001 —— 画像不可用则返回系列级范本
        return skeleton
    tree = profile.clock_tree
    if not tree:
        return skeleton

    from knowledge.loaders.mx_skeleton import _clock_regs_from_tree

    regs = _clock_regs_from_tree(tree)
    skeleton = skeleton.replace("<PLLM>", str(regs.get("pll_m", "8")))
    skeleton = skeleton.replace("<PLLN>", str(regs.get("pll_n", "336")))
    skeleton = skeleton.replace("<PLLP>", str(regs.get("pll_p", "RCC_PLLP_DIV2")))
    skeleton = skeleton.replace("<PLLQ>", str(regs.get("pll_q", "7")))
    skeleton = re.sub(
        r"FLASH_LATENCY_<N>",
        str(regs.get("flash_latency", "FLASH_LATENCY_5")),
        skeleton,
    )
    return skeleton


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    store = ReferenceTemplateStore()
    print("参考范本:", store.list_references())
    for sid in store.list_references():
        tpl = store.get(sid)
        if tpl is None:
            continue
        print(f"\n=== {sid} ({tpl['series']} / {tpl['core']} / {tpl['max_clock_mhz']}MHz) ===")
        print("  适用:", tpl["compatible_chips"])
        print("  说明:", str(tpl["structure_note"])[:60], "...")
        print("  骨架长度:", len(tpl["main_c_skeleton"]), "字符")
    print("\n归档:", store.archive_all(), "个新范本")
